version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  assignees:
  - dotKuro
  - goloroden
  - strangedev
  - yeldiRium
  labels:
  - Dependencies
  allow:
  - dependency-type: direct
  commit-message:
    prefix: chore
    prefix-development: chore
